// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMqMt9jb-pMU1hqYemHA6bf6CKFFLd2gU',
    appId: '1:862045725600:web:9a69250254ee617937bac5',
    messagingSenderId: '862045725600',
    projectId: 'ampdefender-9bf8e',
    authDomain: 'ampdefender-9bf8e.firebaseapp.com',
    databaseURL: 'https://ampdefender-9bf8e-default-rtdb.firebaseio.com',
    storageBucket: 'ampdefender-9bf8e.firebasestorage.app',
    measurementId: 'G-PKDL90JTXQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsTiLsylhSM30jL7qlgnsYKoLI9_SulLw',
    appId: '1:862045725600:android:901c7807c13252ad37bac5',
    messagingSenderId: '862045725600',
    projectId: 'ampdefender-9bf8e',
    databaseURL: 'https://ampdefender-9bf8e-default-rtdb.firebaseio.com',
    storageBucket: 'ampdefender-9bf8e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCT8Q-2rrhMXyhLhbTaSgPbLg10engPxw',
    appId: '1:862045725600:ios:c58c4ae47242a7d637bac5',
    messagingSenderId: '862045725600',
    projectId: 'ampdefender-9bf8e',
    databaseURL: 'https://ampdefender-9bf8e-default-rtdb.firebaseio.com',
    storageBucket: 'ampdefender-9bf8e.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCT8Q-2rrhMXyhLhbTaSgPbLg10engPxw',
    appId: '1:862045725600:ios:c58c4ae47242a7d637bac5',
    messagingSenderId: '862045725600',
    projectId: 'ampdefender-9bf8e',
    databaseURL: 'https://ampdefender-9bf8e-default-rtdb.firebaseio.com',
    storageBucket: 'ampdefender-9bf8e.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMqMt9jb-pMU1hqYemHA6bf6CKFFLd2gU',
    appId: '1:862045725600:web:ad906740b3ac7c1e37bac5',
    messagingSenderId: '862045725600',
    projectId: 'ampdefender-9bf8e',
    authDomain: 'ampdefender-9bf8e.firebaseapp.com',
    databaseURL: 'https://ampdefender-9bf8e-default-rtdb.firebaseio.com',
    storageBucket: 'ampdefender-9bf8e.firebasestorage.app',
    measurementId: 'G-KCRZ9RD0JZ',
  );
}
